In [1]:
import pandas as pd
import os

In [ ]:
# merge all correlation df, image df, and prompt df

In [24]:
prompt_df_paths = [
    "./prompt_0.csv",
    "./prompt_5000.csv",
    "./prompt_10000.csv",
    "./prompt_15000.csv",
    "./prompt_20000.csv",
    "./prompt_25000.csv",
    "./prompt_30000.csv",
    "./prompt_35000.csv",
]

merged_df = pd.DataFrame()
for path in prompt_df_paths:
    df = pd.read_csv(path)
    merged_df = pd.concat([merged_df, df])

# merge row with same text and create a dictionary to map old id to new id
id_dict = {}
text_dict = {}

for i, row in merged_df.iterrows():
    id = row.id
    text = row.text
    if text in text_dict:
        id_dict[id] = text_dict[text]
    else:
        text_dict[text] = id
        id_dict[id] = id

# only keep rows with values in id_dict
merged_df = merged_df[merged_df.id.isin(text_dict.values())]
merged_df

# merged_df.to_csv("./prompt.csv", index=False)

,id,text,emb
0,06784ff5-144a-4e0d-abbd-5258c9ef92bc,"a portrait of a female robot made from code, v...",[-6.34867400e-02 -1.07782418e-02 -1.30121270e-...
1,4d4c98c4-ca5c-4c24-adeb-013f1c980f21,a portrait of a female robot made from a cloud...,[-4.73030023e-02 -5.42605529e-04 2.76418533e-...
2,9590beda-118c-4f35-9022-aa796d3750a0,"only memories remain, trending on artstation",[ 1.09050974e-01 -6.31868243e-02 1.77967697e-...
3,1f6f8dea-12c1-46ed-887d-2172b97aba43,dream swimming pool with nobody,[ 4.24117558e-02 3.82792726e-02 1.06894318e-...
4,8997837a-1cf0-4dcc-a6f2-9b36e36faa04,a dog doing weights. epic oil painting.,[-5.19250743e-02 -1.89416837e-02 3.93706337e-...
...,...,...,...
4995,91a63113-6a53-4ba7-a8d9-ce7114047436,beautiful portrait of a female Doctor who look...,[-6.56616241e-02 5.06698154e-02 2.42030565e-...
4996,9c161c9e-1bef-4c71-979b-991b2d4dafe3,Bowser from Super Mario drinking a glass of wine,[-3.67081687e-02 6.12371275e-03 -1.99696869e-...
4997,dc629b85-fda3-453a-9992-f25344abfa9d,"A giant amorphous slime creature, walking into...",[-2.95629185e-02 -1.14093842e-02 1.13842040e-...
4998,161dd043-8499-42a9-a596-a7b7e69c2119,"Super Mario as Luke Skywalker in Star Wars, mo...",[-5.87914959e-02 -1.56426020e-02 -1.05990069e-...
4999,faf32b88-e8bc-449e-acea-2586978eb6eb,pin-up imperial guard warhammer,[-8.88757184e-02 5.68240471e-02 -1.20617403e-...

In [30]:
pairs_df_paths = [
    "./pairs_0.csv",
    "./pairs_5000.csv",
    "./pairs_10000.csv",
    "./pairs_15000.csv",
    "./pairs_20000.csv",
    "./pairs_25000.csv",
    "./pairs_30000.csv",
    "./pairs_35000.csv",
]

merged_df = pd.DataFrame()
for path in pairs_df_paths:
    df = pd.read_csv(path)
    merged_df = pd.concat([merged_df, df])

# map prompt_id to new id in id_dict
merged_df["prompt_id"] = merged_df["prompt_id"].map(id_dict)

merged_df.to_csv("./pairs.csv", index=False)

In [35]:
correlation_df_paths = [
    "./correlation_0.csv",
    "./correlation_5000.csv",
    "./correlation_10000.csv",
    "./correlation_15000.csv",
    "./correlation_20000.csv",
    "./correlation_25000.csv",
    "./correlation_30000.csv",
    "./correlation_35000.csv",
]

merged_df = pd.DataFrame()
for path in correlation_df_paths:
    df = pd.read_csv(path)
    merged_df = pd.concat([merged_df, df])

# map prompt_id to new id in id_dict
merged_df["prompt_id"] = merged_df["prompt_id"].map(id_dict)

# merge rows with same prompt_id then concat image_id by space
merged_df = merged_df.groupby("prompt_id").agg(
    {"image_id": lambda x: " ".join(x.astype(str))}
)

# reset index
merged_df = merged_df.reset_index()

merged_df.to_csv("./correlation.csv", index=False)

In [36]:

merged_df

,prompt_id,image_id
0,00021a51-daca-4c9b-bc1a-8dfb000a608c,00029470_00 00029470_01 00029470_02 00029470_0...
1,0005e7ff-8935-46ce-a8e9-7de582fdcff6,00014634_00 00014634_01 00014634_02 00014634_0...
2,000689bf-44e3-464c-8ba5-4a892d7fcc2a,00033982_00 00033982_01 00033982_02 00033982_0...
3,00070a8a-8cd4-4e0d-aed1-79f78eb93f69,00018683_00 00018683_01 00018683_02 00018683_0...
4,000a0f21-c3cc-4962-82e3-ae15e7329e83,00038620_00 00038620_01 00038620_02 00038620_0...
...,...,...
34436,fffe447e-a9e9-4ab4-8e82-2722191ee6e1,00030889_00 00030889_01 00030889_02 00030889_0...
34437,fffea8f6-1365-458b-9672-68b2f34822ca,00013560_00 00013560_01 00013560_02 00013560_0...
34438,fffebf93-8832-4e91-91e6-cefeec32c931,00011204_00 00011204_01 00011204_02 00011204_0...
34439,fffeda5c-e6ca-490f-bf62-ef3a5fdfa332,00008686_00 00008686_01 00008686_02 00008686_0...
34440,ffff3e41-448a-439d-9e4a-89efbcd5ad0c,00003041_00 00003041_01 00003041_02 00003041_0...

In [37]:
image_df_paths = [
    "./image_0.csv",
    "./image_5000.csv",
    "./image_10000.csv",
    "./image_15000.csv",
    "./image_20000.csv",
    "./image_25000.csv",
    "./image_30000.csv",
    "./image_35000.csv",
]

merged_df = pd.DataFrame()
for path in image_df_paths:
    df = pd.read_csv(path)
    merged_df = pd.concat([merged_df, df])

merged_df.to_csv("./image.csv", index=False)

40000